apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <Certificate_Data>
    server: <Server_URL>
  name: <Cluster_Name_ARN>
contexts:
- context:
    cluster: <Cluster_Name_ARN>
    user: <Cluster_Name_ARN>
  name: <Cluster_Name_ARN>
current-context: <Cluster_Name_ARN>
kind: Config
preferences: {}
users:
- name: <Cluster_Name_ARN>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - <Cluster_Name>
      command: aws
      env:
      - name: AWS_PROFILE
        value: default
