apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <Your_Server_Certificate>
    server: <Your_OCP_Server_URL>
  name: <Cluster_Name>
contexts:
- context:
    cluster: <Cluster_Name>
    user: admin
  name: admin
current-context: admin
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: <Client_Certificate_Data>
    client-key-data: <Client_Key_Data>